@startuml currency

class currency {
    .. Constructor ..
    Currency(),
    .. Fields ..
    String name,
    Map markets,
    .. Method ..
    def get_diff(self),
    def diff(self, m1, m2)
}
@enduml